apiVersion: v1
kind: Pod
metadata:
  name: busybox-standalone
  namespace: busybox-namespace
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      resources:
        requests:
          memory: "100Mi"
          cpu: "200m"
        limits:
          memory: "200Mi"
          cpu: "400m"
