apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-service-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: restricted-sa
    namespace: default
roleRef:
  kind: Role
  name: pod-service-reader-role
  apiGroup: rbac.authorization.k8s.io
